/**
 * Qué trajo cada versión del sistema.
 *
 * La fase 6 de la especificación de credenciales pide «dejar el registro en el
 * módulo de Historial de Versiones». Este sistema no tenía uno: el número de
 * versión vivía en package.json y se veía de refilón en la pantalla de acceso,
 * y lo que había cambiado había que ir a buscarlo al repositorio, donde no
 * entra quien usa el sistema.
 *
 * Así que el registro vive acá y se ve en Configuración. Sirve para lo que de
 * verdad se necesita en el día a día: comprobar que el servidor ya se actualizó
 * y saber qué se supone que trae esta versión.
 *
 * AL PUBLICAR UNA VERSIÓN NUEVA se agrega su línea arriba de todo, con la misma
 * frase con que se describió el cambio. Si falta, la pantalla lo dice: muestra
 * la versión que está corriendo y avisa de que no está en esta lista, que es
 * mejor que callarse.
 *
 * Las versiones anteriores a la 1.58.0 son de antes de este registro.
 */
const VERSIONES = [
  { version: "1.184.0", fecha: "2026-08-29", titulo: "La bitácora se encuentra por el nombre de la persona, que es el que la propia pantalla muestra en su columna" },
  { version: "1.183.0", fecha: "2026-08-29", titulo: "El historial dice quién provocó cada anotación automática: el nombre estaba guardado y la pantalla lo tapaba" },
  { version: "1.182.0", fecha: "2026-08-29", titulo: "Corregir a mano lo que anotó el sistema deja constancia: se guarda lo que decía y quién lo corrigió, y se puede leer ahí mismo" },
  { version: "1.181.0", fecha: "2026-08-29", titulo: "El historial de una persona se ve donde se ve la persona: al cambiar de iglesia, su bitácora se va con ella" },
  { version: "1.180.0", fecha: "2026-08-29", titulo: "La bitácora de un miembro anota cuándo pasó la cosa y no cuándo la tecleó alguien, así que su historial se lee en orden" },
  { version: "1.179.0", fecha: "2026-08-29", titulo: "Un teléfono se encuentra escrito como sea —de corrido, con espacios o entre paréntesis— y a nadie se le conoce desde antes de que naciera" },
  { version: "1.178.0", fecha: "2026-08-29", titulo: "El listado de No Miembros dice lo que se le ha entregado a cada persona, y la ficha se imprime con ese detalle" },
  { version: "1.177.0", fecha: "2026-08-29", titulo: "Corregirle el nombre a una ficha se lo corrige a sus ayudas, y así se la puede encontrar por el nombre bueno" },
  { version: "1.176.0", fecha: "2026-08-29", titulo: "El RUT de alguien ya inscrito se avisa al guardar la ficha y no meses después, y la pregunta lleva a mirarla" },
  { version: "1.175.0", fecha: "2026-08-29", titulo: "La misma señora anotada dos veces se pregunta, y se dice cuántas entregas tiene la ficha que ya existe" },
  { version: "1.174.0", fecha: "2026-08-29", titulo: "Ya se puede contestar a cuántas personas distintas se ha ayudado: el informe de ayudas y las dos cifras del mes en el panel" },
  { version: "1.173.0", fecha: "2026-08-29", titulo: "Inscribirse ya no le borra la historia: su ficha de miembro muestra también lo que se le entregó antes" },
  { version: "1.172.0", fecha: "2026-08-29", titulo: "La ficha de la persona dice lo que se le ha entregado: el registro existía por las ayudas y no las nombraba" },
  { version: "1.171.0", fecha: "2026-08-28", titulo: "El mismo traspaso anotado dos veces también se pregunta: era el agujero que quedaba un módulo más allá del libro" },
  { version: "1.170.0", fecha: "2026-08-28", titulo: "Hacer clic en el saldo de una cuenta lleva a su cartola —a ver esa plata— y no a editarle el nombre" },
  { version: "1.169.0", fecha: "2026-08-28", titulo: "El libro empieza arriba: el saldo de cada cuenta muestra las que tienen algo y pliega las que están en cero, de 1.950 px a 770" },
  { version: "1.168.0", fecha: "2026-08-28", titulo: "Las cifras caben enteras en su tarjeta —y si no, la letra baja en vez de cortarse— y el dinero se guarda al peso, sin centavos" },
  { version: "1.167.0", fecha: "2026-08-28", titulo: "Un movimiento se encuentra por su monto —con puntos o sin ellos—, el método está en la barra de filtros y el listado se puede acotar a un rango de montos" },
  { version: "1.166.0", fecha: "2026-08-28", titulo: "El respaldo de un egreso se ve, se busca y se pregunta: una columna en el listado, un filtro de «egresos sin respaldo» y un aviso desde el monto que decida la iglesia" },
  { version: "1.165.0", fecha: "2026-08-28", titulo: "Tesorería devuelve papel: balance del período por mes, por categoría y por cuenta; cartola de una cuenta con el saldo corriendo fila a fila; y el comprobante de un movimiento" },
  { version: "1.164.0", fecha: "2026-08-28", titulo: "Mover el saldo inicial de una cuenta que ya tiene movimientos se pregunta antes de guardar, diciendo a cuánto quedaría el saldo" },
  { version: "1.163.0", fecha: "2026-08-28", titulo: "El mismo movimiento anotado dos veces se pregunta antes de guardarse: la cuenta dejó de descontar el doble en silencio" },
  { version: "1.162.0", fecha: "2026-08-28", titulo: "El saldo de una cuenta es lo que hay hoy: la ofrenda de un servicio agendado deja de sumar antes de tiempo, y lo anotado más adelante se dice como «agendado»" },
  { version: "1.161.0", fecha: "2026-08-28", titulo: "El resumen de Tesorería deja de contar como ingreso la plata que solo cambió de bolsillo: los traslados internos se dicen aparte, en «Movido entre cuentas»" },
  { version: "1.160.0", fecha: "2026-08-28", titulo: "El registro de un servicio se llena en menos: seis secciones en vez de nueve, y en el teléfono baja de 2.836 a 2.466 px" },
  { version: "1.159.0", fecha: "2026-08-28", titulo: "La ofrenda entra a Tesorería como llegó: lo que se recibió en efectivo y lo que llegó al banco, cada uno con su método" },
  { version: "1.158.0", fecha: "2026-08-28", titulo: "La asistencia de un servicio deja de admitir números que no existen: nada de negativos, y una multitud se pregunta antes de guardarse" },
  { version: "1.157.0", fecha: "2026-08-28", titulo: "El pasaje se comprueba contra el libro: «Judas 40:900» se pregunta antes de guardarse, con los capítulos de cada libro" },
  { version: "1.156.0", fecha: "2026-08-28", titulo: "La ficha de una persona dice en qué servicios ha servido: cuándo predicó, cuándo coordinó y cuándo leyó el salmo, con su pasaje" },
  { version: "1.155.0", fecha: "2026-08-28", titulo: "Los servicios se buscan por lo que uno recuerda: el tipo, el libro predicado y la cita como se dice —«Juan 3:16»—" },
  { version: "1.154.0", fecha: "2026-08-28", titulo: "El Registro de Servicios suma: los totales de lo que se está viendo van arriba del listado, y hay un informe por mes y por tipo de servicio que se imprime" },
  { version: "1.153.0", fecha: "2026-08-28", titulo: "Registrar dos veces el mismo servicio se pregunta antes de guardar: la ofrenda dejó de poder entrar dos veces a Tesorería sin que nadie lo notara" },
  { version: "1.152.0", fecha: "2026-08-28", titulo: "La vigilia que cruza la medianoche se puede registrar: un término anterior al inicio es del día siguiente, y un servicio de más de doce horas se pregunta" },
  { version: "1.151.0", fecha: "2026-08-28", titulo: "El aporte a la corporación deja de recalcularse solo: cada servicio guarda el porcentaje con que se calculó" },
  { version: "1.150.0", fecha: "2026-08-28", titulo: "El registro de un servicio ya no pide el tema del mensaje: la iglesia no lo usa" },
  { version: "1.149.0", fecha: "2026-08-28", titulo: "Un mensaje largo deja de comerse la campanita entera, y al teléfono le va un extracto que sí cabe" },
  { version: "1.148.0", fecha: "2026-08-28", titulo: "De cada mensaje queda a quiénes fue y qué decía: un envío se abre y se relee, y lo recibido ya no se va con el aviso" },
  { version: "1.147.0", fecha: "2026-08-28", titulo: "Los mensajes tienen ritmo: una cuenta no puede llenar a máquina una campanita que nadie puede apagar" },
  { version: "1.146.0", fecha: "2026-08-28", titulo: "Antes de mandar se sabe a cuántos va —también a una iglesia o a un perfil— y a mucha gente se pregunta dos veces" },
  { version: "1.145.0", fecha: "2026-08-28", titulo: "Los mensajes dejan de perdérsele a quien los recibe: la campanita pone primero lo sin leer y hay una pantalla propia con todo lo que le han escrito" },
  { version: "1.144.0", fecha: "2026-08-28", titulo: "El mensaje llega firmado: quien lo recibe ve de quién viene, en la campanita y en el teléfono" },
  { version: "1.143.0", fecha: "2026-08-28", titulo: "Un mensaje mandado por error se puede retirar: se le quita a quien todavía no lo abrió, y a quien ya lo leyó le queda" },
  { version: "1.142.0", fecha: "2026-08-28", titulo: "«40 de 40 leídos» deja de convertirse solo en «0 de 40»: el conteo se guarda al leerlo y sobrevive al borrado de los avisos" },
  { version: "1.141.0", fecha: "2026-08-28", titulo: "El historial de mensajes se acota a lo que mandó la gente que uno ve: la administración de una iglesia dejó de leer lo que la otra le escribió a los suyos" },
  { version: "1.140.0", fecha: "2026-08-28", titulo: "Se le puede escribir a la gente que usa el sistema: el mensaje llega a su campanita y a su teléfono, y queda dicho a cuántos llegó y cuántos lo leyeron" },
  { version: "1.139.0", fecha: "2026-08-28", titulo: "El RUT se encuentra escrito como sea, la dirección también se busca, y el formulario pide el nombre antes que el trato" },
  { version: "1.138.0", fecha: "2026-08-28", titulo: "De un traslado queda adónde y desde cuándo, y de un fallecimiento su fecha: «quiénes se fueron este año» ya se puede contestar" },
  { version: "1.137.0", fecha: "2026-08-28", titulo: "El tipo de miembro deja de nacer en blanco, avisa cuando no calza con la edad y cuando un menor ya cumplió 18" },
  { version: "1.136.0", fecha: "2026-08-28", titulo: "El adulto responsable de un menor se elige de la membresía: sus datos se leen de su ficha y no se teclean una vez por hijo" },
  { version: "1.135.0", fecha: "2026-08-28", titulo: "Al listado de personas se le puede preguntar por edad y por cuerpo, y ordenarlo por edad" },
  { version: "1.134.0", fecha: "2026-08-28", titulo: "Buscar «María González» encuentra a María González: el buscador va por palabras y sin tildes, en todo el sistema" },
  { version: "1.133.0", fecha: "2026-08-28", titulo: "Al crear a alguien que ya está registrado, el sistema lo dice antes de guardar: se pregunta, no se bloquea" },
  { version: "1.132.0", fecha: "2026-08-28", titulo: "A quien fallece o se traslada se le retira de sus cuerpos: deja de aparecer en la lista, en la planilla del mes y en el aviso de faltas" },
  { version: "1.131.0", fecha: "2026-08-27", titulo: "El sistema avisa de quien lleva muchas faltas seguidas, con las justificadas dichas aparte" },
  { version: "1.130.0", fecha: "2026-08-27", titulo: "Se puede anotar a quien estuvo sin ser del cuerpo: queda como visita, con su constancia, y fuera del porcentaje de nadie" },
  { version: "1.129.0", fecha: "2026-08-27", titulo: "La ficha de cada persona dice cómo ha asistido: su porcentaje del año, cómo le va en cada cuerpo y sus últimas marcas" },
  { version: "1.128.0", fecha: "2026-08-27", titulo: "El informe de asistencia se acota por tipo de actividad: «¿cómo anda la asistencia al Estudio Bíblico?» ya se puede contestar" },
  { version: "1.127.0", fecha: "2026-08-27", titulo: "Una actividad que se repite se crea de una vez: «todos los domingos hasta fin de año», y cada una queda independiente para editarla o borrarla sola" },
  { version: "1.126.0", fecha: "2026-08-27", titulo: "Queda constancia de quién pasó cada lista y cuándo, y corregirla después deja una línea en el Registro de Cambios con lo que cambió" },
  { version: "1.125.0", fecha: "2026-08-27", titulo: "El avance «marcados de convocados» cuenta la lista que uno va a abrir, y el porcentaje se reparte entre los convocados: una lista a medio pasar se dice como tal" },
  { version: "1.124.0", fecha: "2026-08-27", titulo: "La pantalla de Asistencia ofrece los tipos y los motivos que mantiene la iglesia, y una actividad ya creada se puede volver a editar" },
  { version: "1.123.0", fecha: "2026-08-27", titulo: "Al aprobar se ofrece el paso siguiente, cada persona ve lo que ha pedido, y una cuenta no se desactiva dejando solicitudes huérfanas sin avisar" },
  { version: "1.122.0", fecha: "2026-08-27", titulo: "Las solicitudes tienen bandeja, plazo comprometido, hoja impresa con su tramitación y un número que dice de qué iglesia son" },
  { version: "1.121.0", fecha: "2026-08-27", titulo: "Una solicitud no se cierra sin decir qué se resolvió, no se queda sin nadie a cargo y no salta de un cierre a otro sin reabrirse" },
  { version: "1.120.0", fecha: "2026-08-27", titulo: "Las solicitudes que uno tiene a cargo se ven, aunque quien las presentó no sea de sus cuerpos" },
  { version: "1.119.0", fecha: "2026-08-27", titulo: "La presentación de niños, el bautismo y el matrimonio se imprimen siempre a lo ancho" },
  { version: "1.118.0", fecha: "2026-08-27", titulo: "El certificado se imprime en hoja carta o circular, y el diseño se ajusta al papel elegido" },
  { version: "1.117.0", fecha: "2026-08-27", titulo: "La presentación de niños y el matrimonio se imprimen como las hojas que la iglesia usa en papel" },
  { version: "1.116.0", fecha: "2026-08-27", titulo: "A un grupo lo puede dirigir alguien que no está inscrito, y los grupos nacen sin cobrar cuota" },
  { version: "1.115.0", fecha: "2026-08-27", titulo: "En los grupos también sirve gente que no está inscrita en la membresía, y quien se inscribe después se lleva su historial" },
  { version: "1.114.0", fecha: "2026-08-27", titulo: "El libro de la oficina de partes se puede leer entero e imprimir, con su membrete y sus firmas" },
  { version: "1.113.0", fecha: "2026-08-26", titulo: "Documentos pasa a ser la oficina de partes: lo que entra y lo que sale, cada uno con su correlativo" },
  { version: "1.112.0", fecha: "2026-08-26", titulo: "Configuración y permisos al día: el certificado estrena número, la categoría de la directiva se elige, y cada rol dice qué hace con las listas de la iglesia" },
  { version: "1.111.0", fecha: "2026-08-26", titulo: "Vista previa del certificado, en el formato y al emitirlo, sin guardar nada" },
  { version: "1.110.0", fecha: "2026-08-26", titulo: "Los formatos de los certificados los mantiene la iglesia: su texto, qué muestra la hoja y su diseño" },
  { version: "1.109.0", fecha: "2026-08-26", titulo: "La asistencia se lleva por cuerpo: quien está en dos puede quedar justificado en uno y ausente en el otro" },
  { version: "1.108.0", fecha: "2026-08-26", titulo: "Al pasar lista, filtrar por un cuerpo ya no esconde a quien está además en otro" },
  { version: "1.107.2", fecha: "2026-08-26", titulo: "La reparación de la directiva no devolvía a nadie: pedía una fecha de ingreso que esas fichas nunca tuvieron" },
  { version: "1.107.1", fecha: "2026-08-26", titulo: "Se devuelve a los integrantes que la regla de la directiva había retirado por error, y ahora solo maneja a los líderes" },
  { version: "1.107.0", fecha: "2026-08-26", titulo: "Los miembros líderes entran y salen solos de la directiva de su iglesia" },
  { version: "1.106.0", fecha: "2026-08-26", titulo: "El panel ya no muestra las últimas asistencias, y la barra de arriba cabe hasta en un teléfono de 320 px" },
  { version: "1.105.0", fecha: "2026-08-26", titulo: "Revisión de todas las pantallas en el teléfono: 540 cosas que se veían mal, y una prueba nueva que las vigila" },
  { version: "1.104.1", fecha: "2026-08-26", titulo: "El editor de permisos cabía a medias en el teléfono: faltaban las cuatro columnas de acciones" },
  { version: "1.104.0", fecha: "2026-08-26", titulo: "En el teléfono, los botones ya no tapan la fecha y los filtros dejan ver los registros" },
  { version: "1.103.0", fecha: "2026-08-26", titulo: "Optimización completa: entrar pesa 155 KB menos y con señal mala el panel aparece antes" },
  { version: "1.102.0", fecha: "2026-08-25", titulo: "Tres permisos nuevos, cinco ajustes nuevos, y los tipos de actividad y motivos de ausencia los mantiene la iglesia" },
  { version: "1.101.1", fecha: "2026-08-25", titulo: "Tres llaves que se podían conceder y no servían de nada: ahora sí" },
  { version: "1.101.0", fecha: "2026-08-25", titulo: "El menú tiene su buscador de secciones, y el número de acta lo propone el sistema" },
  { version: "1.100.0", fecha: "2026-08-25", titulo: "El acta de reunión se descarga como PDF, con todo lo que tiene y el membrete de la institución" },
  { version: "1.99.1", fecha: "2026-08-25", titulo: "Los asistentes del acta salen de la lista que se pasó, y no de un campo que ofrecía a toda la iglesia" },
  { version: "1.99.0", fecha: "2026-08-25", titulo: "El acta trae el texto del documento adjunto y se enlaza con la lista de asistencia de esa reunión" },
  { version: "1.98.1", fecha: "2026-08-25", titulo: "No se puede apuntar a lo que no se alcanza: se cierra la escritura que ampliaba el propio alcance" },
  { version: "1.98.0", fecha: "2026-08-25", titulo: "Auditoría de aislamiento: diez rutas entregaban datos de otra iglesia, y una dejaba entrar a una cuenta ajena" },
  { version: "1.97.5", fecha: "2026-08-25", titulo: "El archivo del sistema anterior se puede sacar del servidor: terminado el traspaso, ya no tiene para qué quedarse" },
  { version: "1.97.4", fecha: "2026-08-25", titulo: "En las planillas los teléfonos bajan sin el «+», que Excel podía comerse" },
  { version: "1.97.3", fecha: "2026-08-25", titulo: "Queda dicho quién cuida la integridad de los datos, y vigilado que no se le escape ninguna referencia" },
  { version: "1.97.2", fecha: "2026-08-25", titulo: "No se guarda una referencia a un registro que no existe" },
  { version: "1.97.1", fecha: "2026-08-25", titulo: "Cada campo dice cómo se llama: el sistema se puede usar sin ver la pantalla" },
  { version: "1.97.0", fecha: "2026-08-25", titulo: "El informe de asistencia abre en el año en curso, y la base ya sabe buscar por fecha" },
  { version: "1.96.3", fecha: "2026-08-25", titulo: "Una dirección mal escrita ya no deja sin listados a todo el mundo" },
  { version: "1.96.2", fecha: "2026-08-25", titulo: "Una asignación de iglesias mal escrita ya no se guarda vacía: se rechaza y se dice por qué" },
  { version: "1.96.1", fecha: "2026-08-25", titulo: "Una etiqueta sin cerrar ya no se cuela en un acta, y un «<» escrito a mano ya no se come la frase" },
  { version: "1.96.0", fecha: "2026-08-25", titulo: "Los números de las planillas bajan como números, y dos guardados a la vez ya no se traban" },
  { version: "1.95.0", fecha: "2026-08-25", titulo: "Todo lo que se imprime identifica a la institución, dice quién lo emitió y sale sin restos de pantalla" },
  { version: "1.94.0", fecha: "2026-08-25", titulo: "El menú se reordenó por lo que más se usa, y sus grupos se pliegan" },
  { version: "1.93.0", fecha: "2026-08-25", titulo: "Al aprobar una solicitud de ayuda social, la ayuda queda registrada sola" },
  { version: "1.92.1", fecha: "2026-08-25", titulo: "El texto de los botones anchos ya no queda pegado a la izquierda" },
  { version: "1.92.0", fecha: "2026-08-25", titulo: "La base se compacta sola: el espacio de lo borrado vuelve al disco" },
  { version: "1.91.0", fecha: "2026-08-25", titulo: "Cuatro permisos nuevos: mantenimiento, RUT y fecha de nacimiento, imprimir, y tramitar solicitudes de otros" },
  { version: "1.90.0", fecha: "2026-08-25", titulo: "Siete ajustes nuevos: plazos, vigencia de credenciales y valores por defecto al pasar lista" },
  { version: "1.89.0", fecha: "2026-08-25", titulo: "El sistema anotaba con la hora del servidor, no con la de Chile: ahora la zona horaria se elige" },
  { version: "1.88.0", fecha: "2026-08-25", titulo: "La aplicación ahora abre aunque no haya señal, y avisa que no la hay" },
  { version: "1.87.3", fecha: "2026-08-25", titulo: "Apagar los avisos de un aparato ya no falla, y se pueden apagar los huérfanos" },
  { version: "1.87.2", fecha: "2026-08-25", titulo: "El icono de la aplicación ya no sale con el nombre de la iglesia cortado" },
  { version: "1.87.1", fecha: "2026-08-24", titulo: "El aviso de prueba dice de verdad qué falló, y la campanita lleva a sus preferencias" },
  { version: "1.87.0", fecha: "2026-08-24", titulo: "Avisos: la campanita del sistema y los avisos en el teléfono" },
  { version: "1.86.0", fecha: "2026-08-24", titulo: "Las solicitudes ahora se siguen: número, responsable, traslados e historial" },
  { version: "1.85.0", fecha: "2026-08-24", titulo: "La planilla mensual de asistencia de cada cuerpo, para imprimir y firmar" },
  { version: "1.84.1", fecha: "2026-08-24", titulo: "En el teléfono, el aviso de que no hay respaldo ya no se sale de la pantalla" },
  { version: "1.84.0", fecha: "2026-08-24", titulo: "Un registro aparte para las personas que no son de la iglesia y reciben ayuda" },
  { version: "1.83.0", fecha: "2026-08-24", titulo: "El panel abre cuatro veces más rápido cuando la iglesia ya tiene datos" },
  { version: "1.82.0", fecha: "2026-08-24", titulo: "Seis cosas que encontró la revisión del código, y sus arreglos" },
  { version: "1.81.0", fecha: "2026-08-24", titulo: "Cifrar una contraseña ya no deja frenado al resto del sistema" },
  { version: "1.80.0", fecha: "2026-08-24", titulo: "La configuración del sistema, en pestañas" },
  { version: "1.79.0", fecha: "2026-08-24", titulo: "Una imagen con transparencia ya no se sube con el fondo relleno de blanco" },
  { version: "1.78.0", fecha: "2026-08-24", titulo: "Credenciales · Fase 6: permisos, auditoría e historial de versiones" },
  { version: "1.77.0", fecha: "2026-08-24", titulo: "Credenciales · Fase 5: la verificación pública y el aviso de vencimiento" },
  { version: "1.76.0", fecha: "2026-08-24", titulo: "Credenciales · Fase 4: el diseño, la impresión y el QR leído del papel" },
  { version: "1.75.0", fecha: "2026-08-24", titulo: "Credenciales · Fase 3: crear, emitir y revocar" },
  { version: "1.74.0", fecha: "2026-08-24", titulo: "Credenciales · Fase 2: los recursos institucionales y la clave del QR" },
  { version: "1.73.0", fecha: "2026-08-24", titulo: "Credenciales · Fase 1: la base, el número de serie y la limpieza" },
  { version: "1.72.1", fecha: "2026-08-23", titulo: "El sistema se llama «Gestión de Iglesias»" },
  { version: "1.72.0", fecha: "2026-08-23", titulo: "Un buscador general, arriba de todo" },
  { version: "1.71.0", fecha: "2026-08-23", titulo: "Más cosas que se deciden en Configuración y no en el código" },
  { version: "1.70.0", fecha: "2026-08-23", titulo: "Las secciones de una ficha, en pestañas" },
  { version: "1.69.0", fecha: "2026-08-23", titulo: "La tesorería de un cuerpo, aparte de la de la iglesia" },
  { version: "1.68.0", fecha: "2026-08-23", titulo: "Que se pueda personalizar todo lo que el sistema comprueba" },
  { version: "1.67.0", fecha: "2026-08-23", titulo: "Que el editor de permisos muestre todo lo que el sistema comprueba" },
  { version: "1.66.0", fecha: "2026-08-23", titulo: "Ver en qué se está usando el disco" },
  { version: "1.65.0", fecha: "2026-08-23", titulo: "Avisar cuando hace mucho que nadie se baja el respaldo" },
  { version: "1.64.0", fecha: "2026-08-23", titulo: "Que se pueda usar sin ver la pantalla, y cuatro detalles menores" },
  { version: "1.63.0", fecha: "2026-08-23", titulo: "Contraseñas que protejan, subida con permiso y números que no se repiten" },
  { version: "1.62.0", fecha: "2026-08-23", titulo: "Que solo se pueda pasar lista a quien está convocado" },
  { version: "1.61.0", fecha: "2026-08-23", titulo: "Que la planilla entre por la misma puerta que el formulario" },
  { version: "1.60.0", fecha: "2026-08-23", titulo: "Que las fechas y los montos tengan sentido antes de guardarse" },
  { version: "1.59.0", fecha: "2026-08-23", titulo: "Que borrar no deje datos colgando" },
  { version: "1.58.0", fecha: "2026-08-23", titulo: "Cerrar la lista de opciones de los módulos que no se pueden ver" },
];

module.exports = { VERSIONES };
